// NOTES/src-2.2上课练习合并使用reducer/pages/Search/index.jsx
import React, { Component } from "react";

import PubSub from "pubsub-js";
import { TOPIC } from "../../constans";
export default class Search extends Component {
  state = { searchName: "" };

  handleChange = (e) => {
    this.setState({
      searchName: e.target.value.trim(),
    });
  };

  handleClick = () => {
    PubSub.publish(TOPIC, this.state.searchName);
  };
  handle2 = () => {
    PubSub.publish()
  };
  handle3 = () => {
    PubSub.publish()
  };
  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input
            type="text"
            placeholder="enter the name you search"
            value={this.state.searchName}
            onChange={this.handleChange}
          />
          <button onClick={this.handleClick}>Search</button>
        </div>
        <button onClick={this.handle2}>显示全部</button>
        <button onClick={this.handle3}>显示部分</button>
      </section>
    );
  }
}

// src.1/Views/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        v-model="searchName"
        placeholder="enter the name you search"
      />
      <button @click="sendSearchName">Search</button>
    </div>
  </section>
</template>
<script type="text/ecmascript-6">
export default {
  name: "Search",
  data() {
    return {
      searchName: "",
      oldsSearchName: "",
    };
  },
  methods: {
    sendSearchName(searchName) {
      const serchName = this.searchName.trim(); //去除空格
      if (!searchName) {
        //如果用户没有输入内容,不发送请求
        alert("请输入搜索内容");
        return;
      }
      if (this.oldsSearchName === searchName) {
        return;
      }
      this.$bus.$emit("sendSearchName", serchName);
      this.oldsSearchName = searchName;
    },
  },
};
</script>

<style scoped>
</style>
